### PR TITLE
MC-7185 extensibility

### LINKED ISSUE #1: Support more import strategies (e.g. ES6 imports)

### PR DESCRIPTION
**Pull request by prollynomial**
When we use this in the new UI, we'll just pass in our own authenticator and resolver.

Our custom authenticator will do nothing since the session cookie will be passed with requests automatically. Our custom resolver will wait for the websocket event for task completion to be received, and then resolve it's promise with the entity data. This will stop us from polling on the frontend.

The core of `index.js` stays the same (using proxies, etc) even though git didn't recognize `index.js -> src/index.js` as a rename.

(fix #1)

### CODE REVIEW

**Comment by franzpgarcia** [comment]
fetch doesn't add the session cookie by default. You need to include `withCredentials: true` in fetch.

**Comment by prollynomial** [comment]
~Oh ok, I may have to expose fetch directly then.~ I'm going to rethink where I cut the responsibilities, since there's a way for the resolver to set `credentials: true`, but no way for the authenticator to do the same.

**Comment by franzpgarcia** [comment]
I think we can put this in a public repo on npm.

**Comment by prollynomial** [comment]
Reminder to review @franzpgarcia @simongodard - thanks in advance!

**Review by franzpgarcia — APPROVED** [review]

**Pull request merged**
